# 基本配置
server:
  port: 80
  servlet:
    context-path: /

# debug模式
debug: false

# spring配置
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # 彩色终端支持
  output:
    ansi:
      enabled: detect


#MyBatisPlus配置
mybatis-plus:
  # java目录: classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # resource目录: classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/wqb/mappers/xmls/**/*.xml
  # 别名包扫描路径
  typeAliasesPackage: com.wqb.domains
  # MyBatis-Plus 全局策略配置
  global-config:
    # DB策略配置
    db-config:
      # 全局默认主键类型 :
      # INPUT 用户输入ID
      # ID_WORKER 全局唯一ID，Long类型的主键
      # ID_WORKER_STR 字符串全局唯一IDs
      # UUID 全局唯一ID，UUID类型的主键
      # NONE 该类型为未设置主键类型
      id-type: AUTO
      # 字段策略
      field-strategy: not_null
      # 表名是否使用下划线命名
      table-underline: true
      #  entity自动生成的 where条件中String类型字段是否使用LIKE
      column-like: false
      # 数据库类型
      db-type: mysql
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0

  #原生MyBatis配置
  configuration:
    # 是否开启下划线转驼峰命名规则
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    # cache-enabled: false
    # 配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

#浏览器环境配置项，参见BrowserProperties
app:
  security:
    # 验证码配置 参见ValidateCodeProperties
    code:
      #图片验证码配置项，参见ImageCodeProperties
      image:
        length: 4
        width: 60
        height: 30
        expireIn: 3600
        # 配置需要图形验证码验证的url, 两个验证码如果配的url中相同部分则短信优先级要高
        url:

      #短信验证码配置项，参见SmsCodeProperties
      sms:
        length: 6
        expireIn: 60
        # 配置需要短信验证码验证的url
        url:  /user/register/**

    #社交登录功能拦截的url,参见SocilaProperties
    social:
      # 处理的url
      filterProcessesUrl: /login/connect

      #QQ登录配置，参见QQProperties
      qq:
        app-id:
        app-secret:
        providerId: qq

      #微信登录配置，参见WeixinProperties
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin

    #认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
    oauth2:
      # 第三方客户端配置
      clients:
        - clientId: app
          clientSecret: appsecret
          accessTokenValidateSeconds: 3600
          refreshTokenValidateSeconds: 2592000
        - clientId: test
          clientSecret: test
      #OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
      tokenStore: jwt
      #使用jwt时为token签名的秘钥
      jwtSigningKey: aXo3t%12_Ao
---
# 开发环境
spring:
  profiles: dev

  datasource:
#    url: jdbc:mysql://192.168.1.10:3306/wqb_yjz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: xw
#    password: Xw9999
    url: jdbc:mysql://www.lazyor.com:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: caipiao
    password: caipiao...
  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000

mybatis-plus:
  configuration:
    cache-enabled: false


logging:
  level:
    root: info
    com:
      wqb: debug
    org:
      springframework:
        security: debug

#    org:
#      springframework: debug
#    org.springframework.boot.autoconfigure: info
#    org.springframework.web.servlet.view.freemarker: info
---

# 生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/accounting?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  configuration:
    cache-enabled: true

logging:
  level:
    root: info
  path: /log
  file: accounting.log
---
